
import { TableData, ColumnType } from "../types";

/**
 * 로컬 로직을 사용하여 현재 스키마 상태를 기반으로 PostgreSQL DDL SQL을 생성합니다.
 * 외부 API(Gemini)를 호출하지 않으므로 즉시 응답합니다.
 */
export const generateSQL = (tables: TableData[], relations: any[]): string => {
  let sql = `-- Generated by SchemaViz (Local Export)\n-- Target: PostgreSQL\n-- Generated at: ${new Date().toLocaleString()}\n\n`;

  // 1. Create Tables
  tables.forEach(table => {
    sql += `CREATE TABLE "${table.name}" (\n`;
    
    const columnDefinitions = table.columns.map(col => {
      let line = `  "${col.name}" ${mapDataType(col.type)}`;
      
      if (col.isPK) line += ` PRIMARY KEY`;
      if (col.isUnique && !col.isPK) line += ` UNIQUE`;
      if (!col.isNullable) line += ` NOT NULL`;
      
      return line;
    });
    
    sql += columnDefinitions.join(',\n');
    sql += `\n);\n\n`;
  });

  // 2. Add Foreign Key Constraints
  relations.forEach((rel, index) => {
    const sourceTable = tables.find(t => t.id === rel.source);
    const targetTable = tables.find(t => t.id === rel.target);
    
    if (sourceTable && targetTable && rel.sourceHandle && rel.targetHandle) {
      const sourceCol = sourceTable.columns.find(c => c.id === rel.sourceHandle);
      const targetCol = targetTable.columns.find(c => c.id === rel.targetHandle);
      
      if (sourceCol && targetCol) {
        const fkName = `fk_${targetTable.name}_${targetCol.name}_${index}`;
        sql += `ALTER TABLE "${targetTable.name}" \n  ADD CONSTRAINT "${fkName}" \n  FOREIGN KEY ("${targetCol.name}") \n  REFERENCES "${sourceTable.name}" ("${sourceCol.name}");\n\n`;
      }
    }
  });

  return sql;
};

// Helper to map UI types to SQL types
const mapDataType = (type: ColumnType): string => {
  switch (type) {
    case 'VARCHAR': return 'VARCHAR(255)';
    case 'INTEGER': return 'INTEGER';
    case 'BOOLEAN': return 'BOOLEAN';
    case 'DATE': return 'DATE';
    case 'TIMESTAMP': return 'TIMESTAMP';
    case 'UUID': return 'UUID';
    case 'TEXT': return 'TEXT';
    case 'JSON': return 'JSONB';
    default: return 'VARCHAR(255)';
  }
};
